name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: YOLO_crop
            target: x86_64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v2

      - name: Install Valgrind
        run: |
          sudo apt install valgrind > /dev/null
          echo "Valgrind installed!"

      - name: setup
        run: ./setup.bash

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
